name: isf_app
description: "Official Mobile App for Iykhei Sport Festival (ISF)"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  webview_windows: ^0.2.0
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  connectivity_plus: ^6.1.4
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.2
  intl: ^0.20.2
  http: ^1.2.0
  screenshot: ^3.0.0
  path_provider: ^2.0.15




  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"



flutter:


  uses-material-design: true

  assets:
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/paystacklogo.png
    - assets/images/isfmarathon.jpeg
    - assets/images/isfbanner.png
    - assets/images/btn-download-google.png
  
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.ttf